import Image from "next/image";
import Link from "next/link";
import { FaBullseye, FaEye, FaHandshake, FaBalanceScale, FaBook, FaUserShield, FaPeopleArrows } from "react-icons/fa";
import InnerBanner from "@/components/innerBanner/InnerBanner";
import styles from "./AboutUs.module.css";
import dynamic from "next/dynamic";
import TeamSection from "./TeamSection";
import AboutCTA from "./AboutCTA";
import { getAboutus, getMissionVission, getTeams } from "@/lib/functions";

export const metadata = {
  title: "About Us",
  description: "Generated by create REDVision Technologies.",
};

const coreValues = [
  { icon: <FaBullseye />, label: "Client-Centric Advice" },
  { icon: <FaBalanceScale />, label: "Transparency" },
  { icon: <FaUserShield />, label: "Ethical Conduct" },
  { icon: <FaPeopleArrows />, label: "Goal-Based Planning" },
  { icon: <FaHandshake />, label: "Long-Term Relationships" },
  { icon: <FaBook />, label: "Financial Literacy" },
];

const Introduction = async ({ aboutData }) => {
  return (
    <div className="main-section">
      <div className="max-w-screen-xl mx-auto">
        {aboutData[0] && (
          <section className={styles.aboutSection}>
            <div className={styles.aboutcontainer}>
              <div className={styles.imageWrapper}>
                <Image
                  src={aboutData[0].image?.url}
                  alt="About BALAJI FINVEST"
                  width={500}
                  height={600}
                  className={styles.image}
                />
              </div>

              <div className={styles.content}>
                <h2 className={styles.title}>{aboutData[0].title}</h2>
                <div
                  className={styles.paragraph}
                  dangerouslySetInnerHTML={{ __html: aboutData[0].description }}
                />
              </div>
            </div>
          </section>
        )}
      </div>
    </div>
  );
};

const MlmLegacy = async () => {
  return (
    <div className="main-section bg-white">
      <div className="max-w-screen-xl mx-auto">
        <section className={styles.aboutSection}>
          <h2 className={`${styles.title} mt-2`}>A Legacy Built on Trust 🏛️</h2>
          <div className={styles.legacySection}>
            <div className={styles.legacycontent}>
              <p>
                <strong>MLAM INVESTECH</strong> was founded by our visionary <strong>Late Mr. Mohan Lal Mukhi</strong> (fondly known as <strong>ML</strong>),
                a Chartered Accountant by qualification but a true believer in equity investing at heart. At a time
                when awareness around equity was limited, his mission was to spread the culture of <strong>disciplined investing</strong>.
              </p>
              <p className="mt-4">
                He was joined by his nephew, <strong>Mr. Atul Mukhi (AM)</strong>, a Delhi University graduate, who shared the same
                <strong>client-focused vision</strong>. Together, they built <strong>MLAM INVESTECH</strong> as a <strong>boutique investment distribution firm</strong> —
                focused on customized investment strategies aligned with tax planning, individual goals, and prudent risk-taking.
              </p>
              <p className="mt-4">
                Their commitment to <strong>personalized service</strong> and <strong>ethical practices</strong> helped <strong>MLAM INVESTECH</strong> become a trusted name in financial circles.
              </p>
            </div>
            <div className={styles.legacyImageWrapper}>
              <Image
                src="/images/aboutus/legacy.jpg"
                alt="Legacy of MLAM"
                width={500}
                height={600}
                className={styles.image}
              />
            </div>
          </div>
        </section>
      </div>
    </div>
  );
};

const MlmApproach = async () => {
  return (
    <div className="main-section">
      <div className="max-w-screen-xl mx-auto">
        <section className={styles.aboutSection}>
          <h2 className={styles.title}>A New-Age Approach with the Same Values 🌟</h2>
          <div className={`${styles.legacySection} reverse`}>
            <div className={styles.legacyImageWrapper}>
              <Image
                src="/images/aboutus/newjourney.jpg"
                alt="Viren Mukhi"
                width={500}
                height={600}
                className={styles.image}
              />
            </div>
            <div className={styles.legacycontent}>
              <p>
                Today, the legacy continues with the <strong>third generation — Viren Mukhi</strong>, who brings a blend of
                <strong>technical knowledge, digital innovation, and analytical acumen</strong>. A <strong>B.Tech graduate</strong> currently pursuing his MBA from
                a top Delhi institute, Viren actively works alongside his father to <strong>modernize the firm’s offerings</strong>.
              </p>
              <p className="mt-4">
                He has introduced <strong>digitized investment processes</strong> while preserving the firm’s hallmark <strong>personalized approach</strong>.
                With a <strong>growing team</strong> trained in the same <strong>client-centric ethos</strong>, <strong>MLAM INVESTECH</strong> is well-equipped to serve
                the <strong>evolving needs</strong> of today’s investors.
              </p>
              <p className="mt-4">
                This combination of <strong>deep-rooted experience</strong> and <strong>future-focused execution</strong> empowers us to deliver better results —
                <strong>quickly, efficiently, and always in the best interest of our clients</strong>.
              </p>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
};

const MissionVisionValues = async ({ aboutotherdata }) => {
  return (
    <div className="main-section py-16 bg-[var(--rv-white)]">
      <div className="max-w-screen-xl mx-auto px-4">
        <div className={styles.mvvContainer}>
          {/* Mission & Vision */}
          <div className={styles.wrapper}>
            {/* Mission */}
            <div className={styles.card}>
              <div className={styles.content}>
                <h3 className={styles.title}>
                  <FaBullseye className={styles.icon} />
                  <span className={styles.highlight}>Our Mission</span>
                </h3>
                <p className={styles.text}>
                  To empower individuals, families, and businesses to make informed investment decisions by offering
                  ethical, personalized, and goal-oriented financial solutions — rooted in trust, transparency, and long-term value creation.
                </p>
              </div>
              <div className={styles.imageWrapper}>
                <Image
                  src="/images/aboutus/mission.webp"
                  alt="Our Mission"
                  width={500}
                  height={300}
                  className={styles.image}
                />
              </div>
            </div>

            {/* Vision */}
            <div className={`${styles.card} ${styles.reverse}`}>
              <div className={styles.content}>
                <h3 className={styles.title}>
                  <FaEye className={styles.icon} />
                  <span className={styles.highlight}>Our Vision</span>
                </h3>
                <p className={styles.text}>
                  To be recognized as one of India’s most trusted and forward-thinking investment distribution firms —
                  seamlessly blending traditional values with modern innovation to help clients grow, protect, and pass on their wealth across generations.
                </p>
              </div>
              <div className={styles.imageWrapper}>
                <Image
                  src="/images/aboutus/vision.webp"
                  alt="Our Vision"
                  width={500}
                  height={300}
                  className={styles.image}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default async function AboutUs() {
  const aboutData = await getAboutus();
  const aboutotherdata = await getMissionVission();
  const aboutteamdata = await getTeams();
  return (
    <div className={styles.aboutPage}>
      <InnerBanner pageName="About Us" />
      <Introduction aboutData={aboutData} />
      <MlmLegacy />
      <MlmApproach />
      <MissionVisionValues aboutotherdata={aboutotherdata} />
      {/* <KeyHighlight /> */}
      {/* <BalajiComitment />  */}
      <TeamSection aboutteamdata={aboutteamdata} />
      <AboutCTA />
    </div>
  );
}
